0LNetworkCommunity/libra-framework

.github/actions/build_env/action.yaml, .github/workflows/ci.yaml, .github/workflows/cleanliness.yaml, .github/workflows/move.yaml, .github/workflows/nuke-ci.yaml, Cargo.lock
Fix github actions caching with dual caches and split tests into multiple parallel jobs. Uses github hosted runners again.
Had to write own caching action for sccache here: https://github.com/0o-de-lally/sccache-action. Bless you my fragile and tender rust compile cache.
=> [CI] github actions compile cache fixes

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, framework/cached-packages/Cargo.toml, tools/txs/tests/transfer.rs
=> [deps] Update diem deps

framework/libra-framework/sources/modified_source/stake.move, framework/libra-framework/sources/ol_sources/epoch_boundary.move, framework/libra-framework/sources/ol_sources/globals.move, framework/libra-framework/sources/ol_sources/oracle.move, framework/libra-framework/sources/ol_sources/proof_of_fee.move, framework/libra-framework/sources/ol_sources/testnet.move, framework/libra-framework/sources/ol_sources/tests/proof_of_fee.test.move, framework/libra-framework/sources/ol_sources/tests/tower.test.move, framework/libra-framework/sources/ol_sources/vouch.move, tools/config/src/host.rs, tools/txs/src/txs_cli.rs
Patching a bug in the validator which didn't include non-current-set validators.
=> Debug vouch

framework/libra-framework/sources/ol_sources/burn.move, framework/libra-framework/sources/ol_sources/ol_account.move, framework/libra-framework/sources/ol_sources/tests/burn.test.move
This is an informational struct and doesn't affect policies.
=> [Move] patch burn tracker

Cargo.lock, framework/Cargo.toml, framework/libra-framework/sources/modified_source/coin.move, framework/libra-framework/sources/modified_source/diem_governance.move, framework/libra-framework/sources/ol_sources/burn.move, framework/libra-framework/sources/ol_sources/epoch_boundary.move, framework/libra-framework/sources/ol_sources/pledge_accounts.move, framework/libra-framework/sources/ol_sources/proof_of_fee.move, framework/libra-framework/sources/ol_sources/tests/burn.test.move, framework/libra-framework/sources/ol_sources/tests/donor_directed.test.move, framework/libra-framework/sources/ol_sources/tests/rewards.test.move, framework/src/builder/framework_generate_upgrade_proposal.rs, framework/src/builder/framework_release_bundle.rs
Fixes an informational struct which tracks global lifetime burns. 
The burn methods being used were not updating trackers.
Also has a minor change to genesis setting of consensus reward at genesis in case that was failing silently
=> [move] fix lifetime burn info

util/dev_setup.sh
This was failing when run by root
```
./util/dev_setup.sh: line 168: sudo: command not found
make: *** [Makefile:53: install] Error 127
```
=> fix(util): conditional sudo for some install_protoc commands

framework/libra-framework/sources/modified_source/stake.move
Bump the validator set uniform voting power from 1 per node to 1 million. Each validator still has same equal weight. This will just allow us to view the weight correctly in the logs, and add more safety around the arithmetic for the leader reputation and chain health.
=> [move] voting power

framework/libra-framework/sources/ol_sources/ol_account.move, framework/libra-framework/sources/ol_sources/slow_wallet.move, framework/libra-framework/sources/ol_sources/tests/slow_wallet.test.move
Slow wallet tracking for unlocked and transferred coins are 3x what they should be. Since `transfer` and `transfer_with_capability` already calls `transfer_check` which adjusts those numbers, these other functions should not call `slow_wallet::maybe_track_slow_transfer` unless there is another entry point for them.
=> [move] remove extra slow wallet tracking

framework/libra-framework/sources/modified_source/stake.move, framework/libra-framework/sources/ol_sources/grade.move, framework/libra-framework/sources/ol_sources/mock.move, framework/libra-framework/sources/ol_sources/musical_chairs.move, framework/libra-framework/sources/ol_sources/tests/stake.test.move, framework/libra-framework/sources/ol_sources/validator_universe.move
Some of our old logic for validator performance was not ported.  We have a gap in v5 and v7 performance metrics that are offered by the node platform. In V5 We were able to track VOTES on proposals, and in V7 we track PROPOSALS.
We have an issue that if a validator has 2 successful proposals and 1 failing proposal they will be "graded" as performant, event if there were one million blocks in the epoch. This is a bug.
=> [move] performance metrics

framework/src/builder/framework_generate_upgrade_proposal.rs
Fixes a bug in the file directory composing function. In the bug, the `save_build` function appends the `script.mv` and `script_sha3` file names to the given `--file-path` path, which is the absolute path to the file including its file name. 
This PR solves that by sending the parent directory of the given `--file-path`.
=> [Move] fix directory bug

framework/libra-framework/sources/ol_sources/epoch_boundary.move, framework/libra-framework/sources/ol_sources/grade.move, framework/libra-framework/sources/ol_sources/tower_state.move
Fixes the 'ARITHMETIC_ERROR' we saw in the epoch 13->14 boundary halt. This is due to the case where the `entry fee` is larger than the actual validator reward given by the system. This causes an arithmetic error due to unsupported signed integers in Move. 
This PR also contains a commit by @sm86 which is already merged in main, and a  fix for a small incorrect variable usage in `grade.move`
=> Fix for arithmetic subtraction error in epoch_boundary

framework/Makefile
This is part of a larger initiative that will encompass the 3 frameworks being formally tested with the Move prover. This first PR separates the tests for each of the frameworks and dynamically tests the files with each framework.
**Next Steps**
- Address the failing tests. Most of which are within the libra-framework
- CI to fail on failed test
=> [ci] formal verification ci

framework/cached-packages/build.rs, framework/libra-framework/sources/ol_sources/epoch_boundary.move, framework/src/builder/framework_generate_upgrade_proposal.rs, framework/src/builder/mod.rs, framework/src/builder/named_addresses.rs, framework/src/builder/release.rs, framework/src/framework_cli.rs, framework/src/lib.rs, framework/src/release.rs, smoke-tests/src/libra_smoke.rs, smoke-tests/tests/balance.rs, smoke-tests/tests/meta.rs, tools/genesis/src/genesis_builder.rs
Bundles for release and upgrade had different options (abi, error_map, source_map). 
There was also an issue with named addresses like @ol_framework, not being picked up on upgrade bundles.
=> [framework] use uniform build options for Move

framework/Makefile, framework/libra-framework/sources/ol_sources/slow_wallet.move, framework/libra-framework/sources/ol_sources/slow_wallet.spec.move
- an addition in pr #157 introduced a bug where the ci would hang on formal verification of `block.move`
- fix `slow_wallet.move` to pass
- only test known passing modules in `libra-framework
=> [fix] formal verification ci

framework/libra-framework/sources/code.move
Allow exempted addresses to upgrade framework with any policy. This allows to bypass upgrades with incompatibility issues by changing the upgrade policy in metadata. 
Example(`Move.toml`):
```
[package]
name = "LibraFramework"
version = "1.0.0"
<--------HERE--------->
upgrade_policy = "arbitrary"
<--------HERE--------->
[addresses]
std = "0x1"
diem_std = "0x1"
diem_framework = "0x1"
diem_token = "0x3"
core_resources = "0xA550C18"
vm_reserved = "0x0"
ol_framework = "0x1"
root = "0x1"
[dependencies]
VendorStdlib = { local = "../vendor-stdlib" }
```
=> [feature] allow exempted addresses to upgrade framework with any policy

Cargo.lock, Cargo.toml, framework/cached-packages/Cargo.toml
Include from diem patch 1
[execution] governance::trigger_epoch() should not evaluate gas use
https://github.com/0LNetworkCommunity/diem/pull/5
[sync] out of the set validators fall back to fullnode network
https://github.com/0LNetworkCommunity/diem/pull/4
=> [deps] update diem deps to 1.6.2-diem.1

framework/libra-framework/sources/ol_sources/oracle.move, framework/libra-framework/sources/ol_sources/tests/tower.test.move, framework/libra-framework/sources/ol_sources/tower_state.move
=> [tower] tower sunset

.github/workflows/ci.yaml
Skip running compatible smoke tests in two cases:
1. the branch is named `breaking/xyz`
2. the last commit on `main`contains the string "[breaking]".
Note: when a dev submits a.PR with known backward *incompatible* changes, they must add "[breaking]" to the PR title so that the CI will ignore compatibility check (otherwise it appears as an unexpected failure, when it is actually expected behavior).
=> [ci] flag to skip framework upgrade compatibility checks [breaking]

Cargo.lock, tools/config/Cargo.toml, tools/config/src/lib.rs, tools/config/src/validator_registration.rs, tools/rescue/src/rescue_tx.rs, tools/rescue/src/session_tools.rs, tools/rescue/src/twin.rs, tools/rescue/tests/rescue_cli_creates_blob.rs, tools/rescue/tests/rescue_cli_framework_upgrade_valid.rs, tools/rescue/tests/rescue_e2e_can_create_genesis.rs, tools/rescue/tests/rescue_e2e_can_restart.rs, tools/rescue/tests/rescue_e2e_full.rs, tools/rescue/tests/twin.rs, tools/txs/Cargo.toml, tools/txs/src/txs_cli_vals.rs
=> [testnet] rescue tools takes a list of validator registrations

.github/workflows/nuke-ci.yaml, .github/workflows/publish.yaml, Cargo.lock, tools/cli/src/node_cli.rs
Now diem exposes some test functions to release builds (instead of testing feature flag), so the the CLI needs a minor update for `libra node` and the CI binaries can be updated. This change was the last needed for 7.0.3 binaries to be officially published.
- GitHub worfklow for releasing ci bins
- Updated cargo dependencies
=> [deps] update diem to version with feature flag cleanup

Cargo.lock, Cargo.toml
This PR brings libra-framework into line with the current diem project transitive dependency set which in turn means we can add new dependencies and not run into version skew errors.
=> Update tokio and related dependencies

.github/actions/build_env/action.yaml, .github/workflows/ci.yaml, .github/workflows/cleanliness.yaml
Fixes problematic caching, believed responsible for CI failures.
=> [ci] remove duplicate keys, add sccache for upgrade tests

.github/workflows/container.yaml, container/Containerfile
This PR adds a Containerfile (aka Dockerfile) that builds a simple container image based on Ubuntu containing the suite of release binaries. CI job is configured to build on tags and on the same ci-bins* branches used to build bare binaries.
At present the CI job only builds an Intel image. Should build for ARM ok on an ARM machine though. We can add
buildx/quemu support for cross-platform builds at a later date, or specify an ARM runner and a matrix. GH just added ARM runners so not sure yet which is the best approach.
=> Add basic container file and CI job

container/Containerfile
The `libra` binary depends on local CA certs which are not installed in the base Ubuntu container.
=> Add missing CA certs package

.github/actions/build_env/action.yaml, .github/workflows/rust-versions.yaml, .vscode/launch.json, tools/cli/src/main.rs
Rust 1.81.1 introduces a panic in the prover, which previously was benign.
See: https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html#new-sort-implementations
Requires updates to diem boogie backend
=> [ci] rustc provisionally pinned to 1.80.1

.github/workflows/container.yaml, .github/workflows/publish.yaml, .github/workflows/rust-versions.yaml, framework/prover.mk, tools/cli/src/move_cli.rs
=> [rust] explicitly exit with error on test failing, workflow fixes

framework/cached-packages/src/libra_framework_sdk_builder.rs, framework/libra-framework/sources/block.move, framework/libra-framework/sources/genesis.move, framework/libra-framework/sources/ol_sources/config/globals.move, framework/libra-framework/sources/ol_sources/epoch_boundary.move, framework/libra-framework/sources/ol_sources/migrations.move, framework/libra-framework/sources/ol_sources/vouch_lib/root_of_trust.move, framework/libra-framework/sources/stake.move, tools/genesis/src/vm.rs, tools/rescue/src/session_tools.rs, tools/testnet/Makefile, tools/testnet/src/cli_main.rs, tools/testnet/src/cli_swarm.rs
Future improvements
There is duplication, between Rust and Move code for setting epoch intervals. The move code should contain the defaults.
=> [testnet] twin initialization patches

framework/libra-framework/sources/ol_sources/donor_voice_governance.move, framework/libra-framework/sources/ol_sources/donor_voice_reauth.move, framework/libra-framework/sources/ol_sources/donor_voice_txs.move, framework/libra-framework/sources/ol_sources/mock.move, framework/libra-framework/sources/ol_sources/ol_account.move, framework/libra-framework/sources/ol_sources/reauthorization.move, framework/libra-framework/sources/ol_sources/tests/community_wallet.test.move, framework/libra-framework/sources/ol_sources/tests/donor_voice.test.move, framework/libra-framework/sources/ol_sources/tests/vouch_validator.test.move, framework/libra-framework/sources/ol_sources/vote_lib/tally/turnout_tally.move, framework/libra-framework/sources/ol_sources/vouch_lib/page_rank_lazy.move, framework/libra-framework/sources/ol_sources/vouch_lib/vouch_limits.move
=> [vouch] patch vouch walk and re-authentication workflows

framework/libra-framework/sources/ol_sources/slow_wallet.move, framework/libra-framework/sources/ol_sources/supply.move
=> [slow wallet] reset transferred to 0 plus global unlock tracker

framework/cached-packages/src/libra_framework_sdk_builder.rs, framework/libra-framework/sources/account.move, framework/libra-framework/sources/ol_sources/community_wallet_advance.move, framework/libra-framework/sources/ol_sources/donor_voice_txs.move, framework/libra-framework/sources/ol_sources/ol_account.move, framework/libra-framework/sources/ol_sources/tests/community_wallet.test.move, framework/libra-framework/sources/ol_sources/tests/donor_voice.test.move, tools/testnet/Makefile, tools/txs/src/txs_cli_community.rs
Migrating from v7 to v8 we had initially introduced a new field to Payment type in donor_voice_txs. Because of the deep nesting of this type present in the v7 mainnet, migrating it is not straightforward. So there had to be a new workflow.
This simplified workflow, requires the signers of the multisig to approve the transaction.
=> [community wallet] refactor advance loan for cw

framework/libra-framework/sources/genesis.move, framework/libra-framework/sources/ol_sources/activity.move, framework/libra-framework/sources/ol_sources/mock.move, framework/libra-framework/sources/ol_sources/ol_account.spec.move, framework/libra-framework/sources/ol_sources/reauthorization.move, framework/libra-framework/sources/ol_sources/slow_wallet.move, framework/libra-framework/sources/ol_sources/tests/cumu_deposits.test.move, framework/libra-framework/sources/ol_sources/tests/filo_migration_test.move, framework/libra-framework/sources/ol_sources/tests/page_rank.test.move, framework/libra-framework/sources/timestamp.move
The checks for is_v8_authorized required knowing if an account had an onboarding timestamp prior to v8. This required some changes to testing and testnet, which were starting the clock at timestamp 0.
Timestamp for testing now starts at 1. This is also generally useful since we can assume most tests and transactions are not happening at genesis.
=> [reauth] cleanup activity checks

tools/config/src/make_yaml_public_fullnode.rs
By default new fullnodes should start sync from beginning of current era.
=> [fullnode] public fullnode should apply transactions since genesis

framework/cached-packages/src/libra_framework_sdk_builder.rs, framework/libra-framework/sources/ol_sources/community_wallet_init.move, framework/libra-framework/sources/ol_sources/donor_voice_txs.move, framework/libra-framework/sources/ol_sources/multi_action.move, tools/txs/src/txs_cli_community.rs
A number of fixes related to community wallets re-joining.
Accounts were unable to process because some checks being done assumed some amount of initialization (assert_authorize).
=> [donor-voice] initialization of donor-voice fixes

framework/libra-framework/sources/ol_sources/migrations/filo_migration.move, framework/libra-framework/sources/ol_sources/slow_wallet.move
We've found an edge case with community wallets making unlocked transactions. The FTW Endowment at some point sent a "re-join" transaction that should only be sent by user accounts. That means it has a mixed up state. Effectively when the balance is checked on the account it shows 0, because there is a SlowWallet data structure which should not be there. Given the incorrect state of zero balance, all unlocked transfers will abort.
Anyhow, This patch prevents the user "re-join" tx from being sent. Also includes a better check on balances for this edge case. 
NOTE: a complete solution would require actually sanitizing the CW that has mixed state, but that's beyond the scope of this patch.
=> [donor-voice] patch cw migration 

framework/libra-framework/sources/ol_sources/community_wallet.move, framework/libra-framework/sources/ol_sources/community_wallet_advance.move, framework/libra-framework/sources/ol_sources/slow_wallet.move, framework/libra-framework/sources/ol_sources/supply.move
Implements comprehensive supply calculation functions and fixes critical magnitude errors in slow wallet supply calculations.
Tested on a Twin Testnet of mainnet which had the community wallet issue described below.
- **`get_cw_advanced()`** - Total community wallet advances/withdrawals
- **`get_cw_remaining_credit()`** - Available credit across all community wallets
- **`get_max_supply()`** - Maximum possible supply from genesis
- **`get_total_supply()`** - Current total supply (post-burns)
- **`get_lifetime_burn()`** - Returns `(burned, recycled)` amounts
- **`get_lifetime_withdrawals()`** - Lifetime withdrawals for specific CW
- **`get_credit_line_bps()`** - Credit line basis points constant
- **`is_advance_initialized()`** - Check if CW has advance feature
- **Deduplicated supply …
=> [view] calculate circulating supply and unlocks

framework/libra-framework/sources/ol_sources/migrations/filo_migration.move, framework/libra-framework/sources/ol_sources/mock.move
V8 Migration can be triggered twice. This is a nasty surprise if you had successfully gotten an account authorized and some coins unlocked. Most structs will be no-op when you try to migrate again. Except for Slow wallet, which will reset the balances back to zero. :(
=> [bug] patch duplicate migrate bug

framework/libra-framework/sources/ol_sources/vouch_lib/vouch.move
The logic for maintaining the revocations_this_epoch count was incorrect: if the user sent two revoke txn in different epochs, the `revocations_this_epoch` counter would become wedged at 2. Then (I suspect) this would lead to the account becoming wedged in a state where it could perform no further revocations due to limit enforcement.
=> Fix revokes per epoch counting

framework/libra-framework/sources/ol_sources/vouch_lib/distance_to_root.move, framework/libra-framework/sources/ol_sources/vouch_lib/page_rank.md
These limit constants are performing essentially the same function in two different parts of the codebase.
The actual value doesn't matter so much, since the goal is just to terminate execution before the runtime kills the process, but it's confusing to have two different values.
=> Make the two instances of MAX_PROCESSED_ADDRESSES have the same value
