0LNetworkCommunity/libra-framework

Cargo.lock
Cargo.toml
tools/genesis/Cargo.toml
tools/genesis/src/helpers.rs
tools/genesis/src/lib.rs
tools/genesis/src/wizard.rs
util/dev-setup.sh

On genesis file configuration and registration we want to confirm with the user what the DNS/IP address should be.

[Genesis] fix validator network host publication

---

tools/genesis/src/github_extensions.rs
tools/genesis/src/main.rs
tools/genesis/src/wizard.rs

- Fix Genesis tooling to allow for registration
- Changes first implemented in 0o-de-lally/libra-v7:release-0.6.9
Tested register and genesis commands

[ Patch ] Fix Genesis tooling

---

.github/actions/build_env/action.yaml
.github/workflows/cleanliness.yaml
tools/config/src/node_yaml.rs
tools/genesis/src/ancestry.rs
tools/genesis/tests/e2e.rs
tools/genesis/tests/json_to_genesis_audit_single.rs
tools/wallet/src/core/mnemonic.rs
tools/wallet/src/key_gen.rs
tools/wallet/src/keys.rs
tools/wallet/src/load_keys.rs
types/src/legacy_types/app_cfg.rs

[CI] Fix CI failing

---

.github/workflows/ci.yaml
.github/workflows/cleanliness.yaml

- Allow ci jobs to run after subsequent commits on a opened PR

[CI] Sync on commit

---

Cargo.lock
framework/Cargo.toml
framework/libra-framework/sources/modified_source/diem_governance.move
framework/libra-framework/sources/modified_source/genesis.move
framework/src/builder/framework_generate_upgrade_proposal.rs
framework/src/builder/framework_release_bundle.rs
tools/genesis/src/vm.rs

Set the genesis val default bid for PoF at 90% per the paper

[move] default POF bid from genesis

---

Cargo.lock

-  [x] more aggressive neuter of "telemetry"

[deps] update to diem 1.6.2-rc.5

---

tools/genesis/Makefile

prepare the dependencies for v6.9 tooling newcomers

[tools] Update Makefile

---

tools/genesis/Makefile
util/dev_setup.sh

[tools] Sirouk rc.10 patches

---

tools/genesis/Makefile
util/dev_setup.sh

Patched the Makefile some more

Sirouk rc.10 patches

---

.github/actions/build_env/action.yaml
framework/libra-framework/sources/modified_source/stake.move
tools/genesis/Makefile
util/dev_setup.sh

Add final changes for release 6.9.0

[release] rc.10 and upgrade ceremony patches

---

framework/libra-framework/sources/ol_sources/ancestry.move
framework/libra-framework/sources/ol_sources/community_wallet.move
framework/libra-framework/sources/ol_sources/mock.move
framework/libra-framework/sources/ol_sources/ol_account.move
framework/libra-framework/sources/ol_sources/tests/account.test.move
framework/libra-framework/sources/ol_sources/tests/burn.test.move
framework/libra-framework/sources/ol_sources/validator_universe.move

[move] ancestry not implemented for account creation

---

docs/core_devs/dev_quick_start.md

@0xzoz @sirouk  anywhere else we need to push these changes for 0lnetwork.dev?

[Docs] udpate dev quick start

---

tools/config/src/config_cli.rs
tools/config/src/make_yaml_public_fullnode.rs

This uses a similar method as the waypoint in order to also fetch the latest genesis.blob from the archive.

[tools] node config to use v7 genesis.blob

---

tools/genesis/src/genesis_builder.rs
tools/genesis/src/testnet_setup.rs

Tesnet helper depended on local source for Move .mrb file

[cli] testnet Move bin path

---

Cargo.lock
framework/cached-packages/src/libra_framework_sdk_builder.rs
framework/libra-framework/sources/account.move
framework/libra-framework/sources/ol_sources/community_wallet_advance.move
framework/libra-framework/sources/ol_sources/donor_voice_txs.move
framework/libra-framework/sources/ol_sources/ol_account.move
framework/libra-framework/sources/ol_sources/tests/community_wallet.test.move
framework/libra-framework/sources/ol_sources/tests/donor_voice.test.move
tools/testnet/Cargo.toml
tools/testnet/Makefile
tools/testnet/src/twin_swarm.rs
tools/testnet/tests/test_swarm_twin_v7_can_submit_tx.rs
tools/testnet/tests/test_swarm_twin_v7_upgrade_new_epoch.rs
tools/txs/src/submit_transaction.rs
tools/txs/src/txs_cli.rs
tools/txs/src/txs_cli_community.rs
types/src/core_types/app_cfg.rs

Missing tests for whether transactions can be submitted after twin startup, and if the epoch boundary will be successful.

[twin] tests for epoch boundary after twin startup

---

framework/libra-framework/sources/ol_sources/founder.move
framework/libra-framework/sources/ol_sources/mock.move
framework/libra-framework/sources/ol_sources/tests/page_rank.test.move
framework/libra-framework/sources/ol_sources/vouch_lib/page_rank.md
framework/libra-framework/sources/ol_sources/vouch_lib/page_rank_lazy.move

This patches some edgecase with the vouch walk, cleans up code, and adds tests.

[move] Page rank score thresholds

---

framework/libra-framework/sources/ol_sources/tests/page_rank.test.move
framework/libra-framework/sources/ol_sources/vouch_lib/vouch_limits.move

Patches previous PR for vouches that didn't update the scaling of vouches for new score thresholds.

[vouch] patch vouch limits from scoring

---

framework/libra-framework/sources/ol_sources/vouch_lib/vouch.move

[move] patch get vouches view function

---

framework/libra-framework/sources/ol_sources/tests/donor_voice_governance.test.move
framework/libra-framework/sources/ol_sources/vote_lib/tally/turnout_tally.move

Makes testing on testnet with limited participation practical.

[tally] reduce the turnout threshold for testnet

---

framework/cached-packages/src/libra_framework_sdk_builder.rs
framework/libra-framework/sources/ol_sources/activity.move
framework/libra-framework/sources/ol_sources/donor_voice_governance.move
framework/libra-framework/sources/ol_sources/donor_voice_migration.move
framework/libra-framework/sources/ol_sources/donor_voice_reauth.move
framework/libra-framework/sources/ol_sources/donor_voice_txs.move
framework/libra-framework/sources/ol_sources/multi_action.move
framework/libra-framework/sources/ol_sources/tests/donor_voice.test.move
framework/libra-framework/sources/ol_sources/tests/donor_voice_governance.test.move
framework/libra-framework/sources/ol_sources/tests/page_rank.test.move
framework/libra-framework/sources/ol_sources/tests/vote_lib/turnout_tally.test.move
framework/libra-framework/sources/ol_sources/tests/vouch_validator.test.move
framework/libra-framework/sources/ol_sources/vote_lib/ballot.move
framework/libra-framework/sources/ol_sources/vote_lib/tally/binary_tally.move
framework/libra-framework/sources/ol_sources/vote_lib/tally/turnout_tally.move
framework/libra-framework/sources/ol_sources/vouch_lib/page_rank_lazy.move
framework/libra-framework/sources/ol_sources/vouch_lib/vouch_txs.move
tools/cli/src/main.rs
tools/storage/src/storage_cli.rs
tools/txs/src/main.rs
tools/txs/src/txs_cli_community.rs

Fixes from twin testnet rc.11.

[reauth] reauth tally refactor, page rank fixes

---

tools/storage/src/download_bundle.rs
tools/storage/src/restore_bundle.rs

Github `contents` api was rate limited at 1000 entries per directory. `Tree` api is noe

[storage] change github api to restore epoch archive

---

framework/libra-framework/sources/ol_sources/community_wallet_advance.move
framework/libra-framework/sources/ol_sources/donor_voice_txs.move
framework/libra-framework/sources/ol_sources/tests/donor_voice.test.move

[donor-voice] add checks on accounts for propose payment

---

Cargo.lock

Cargo.lock had drifted behind the current state of diem/release.

Update locked diem dependencies to current

---

framework/libra-framework/sources/ol_sources/activity.move
framework/libra-framework/sources/ol_sources/donor_voice_migration.move
framework/libra-framework/sources/ol_sources/mock.move
framework/libra-framework/sources/transaction_validation.move

This is a fix to the timestamp malform issue in activity.move

[move] handle malformed timestamps in activity.move

---

framework/libra-framework/sources/ol_sources/vouch_lib/page_rank_lazy.move

Walk score loop was inefficient, and may have led to exits without error code. This is mainly a cleanup PR, which would help make errors explicit and abort.

[vouch] refactor page rank walk_stale

---

framework/libra-framework/sources/ol_sources/libra_coin.move
framework/libra-framework/sources/ol_sources/libra_coin.spec.move
framework/libra-framework/sources/system_coin.move
framework/libra-framework/sources/system_coin.spec.move
framework/prover.mk

Expands and makes pass FV for coin module and libra_coin.

[verification] further formal verification of system_coin, libra_coin

---

framework/libra-framework/sources/ol_sources/vouch_lib/page_rank_lazy.move

User vouch score tuning: constrain depth searched to 4 rather than 5.

[vouch] tune MAX_PATH_DEPTH to 4

---

framework/libra-framework/sources/ol_sources/founder.move
framework/libra-framework/sources/ol_sources/tests/donor_voice.test.move
framework/libra-framework/sources/ol_sources/tests/page_rank.test.move
framework/libra-framework/sources/ol_sources/vouch_lib/page_rank_lazy.move
framework/libra-framework/sources/ol_sources/vouch_lib/vouch.move
framework/libra-framework/sources/ol_sources/vouch_lib/vouch_txs.move

Require N distinct unrelated vouchers
